AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for our CICD PR'

Parameters:
  Environnment:
    Type: String 
    Default: Test 
    AllowedValues: 
      - test 
      - staging 
      - production


Resources:
  TheS3Bucket: 
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environnment}-bucket'
      Tags:
        - Key: Environnment
          Value: !Ref Environnment
      
      
Outputs:
  BucketName:
    Description: 'Name of created S3 Bucket'
    Value: !Ref TheS3Bucket
