name: Deploy AWS Lambda

#event
on:
  push:
    branches:
        - main
    paths: 
        - 'lambda-cicd/**'

jobs:
  deploy-lambda: # Name of our job
    runs-on: ubuntu-latest # Sets or specifies the runner
    steps:
      - uses: actions/checkout@v2
        
      - name: Set Up Python Environnment # Set Up Python Environnment 
        uses: actions/setup-python@v2
        with: 
          python-version: '3.13'

      - name: Install Dependencies # Install my packages
        run: |
            python -m pip install --upgrade pip
            pip install -r lambda-cicd/lambda/requirements.txt -t lambda/


      - name: Configure AWS Credentials # Sets up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: eu-central-1

      - name: Deploy our Lambda Function  # Zip Lambda directory and update Lambda functions
        run: |
            cd lambda/
            zip -r lambda.zip .
            aws lambda update-function-code --function-name my_test_cicd_lambda --zip-file file://lambda.zip

              

  

